### ISSUE TITLE
Consider adding `markdown-code-face` to eigengrau

### ISSUE THREAD

**Issue by daveliepmann** [jackrusher/dotemacs#27]
For context, see https://github.com/jrblevin/markdown-mode/issues/273. A bug/feature/change in the latest release of markdown-mode causes a white background—blinding, for those using dark themes—for all `inline code` unless `markdown-code-face` is defined.

The simple fix is `(set-face-attribute 'markdown-code-face nil :background nil)`; I am looking into adding that to eigengrau circa line 493.

**Comment by jackrusher** [comment]
How's that PR coming? :)
